scene: bellevue_150th_newport
fps: 30
data_dir: data
raw_dir: ${.data_dir}/raw/${.scene}
interim_dir: ${.data_dir}/interim/${.scene}
processed_dir: ${.data_dir}/processed/${.scene}
video: E:/Education/Doktori_iskola/research/FinalPhase/Bellevue/Bellevue_150th_Eastgate/Bellevue_150th_Eastgate__2017-09-10_18-08-24.mp4

# OPTICS clustering parameters (optional override)
cluster:
  min_samples: 200
  max_eps: 0.1
  xi: 0.1

class_map:
  car: 2
  bus: 5
  bicycle: 1
  person: 0
  truck: 7
  traffic_light: 9
